version: '3'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=team_data
      - MYSQL_USER=mohamed
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80

 

